export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS'

export const GET_CODE_FALIURE = 'GET_CODE_FALIURE'

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'

export const ADD_CATEGORY_FALIURE = 'ADD_CATEGORY_FALIURE'

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'

export const GET_CATEGORY_FALIURE = 'GET_CATEGORY_FALIURE'
